name: Python Check

on:
  push:
    branches:
      - main

jobs:
  check-python:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Mostrar versión de Python
        run: python --version

      - name: Mensaje final
        run: echo "Workflow ejecutado correctamente"